# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Places
    url: tags/
    weight: 20
  - name: Years
    url: categories/
    weight: 30
